In [1]:
import pandas as pd
import yfinance as yf

In [4]:
# 1. Initialize the Ticker object
aapl = yf.Ticker("AAPL")

# 2. Get historical market data
# Valid periods: 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max
historical_data = aapl.history(period="6mo")

historical_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-11-03 00:00:00-05:00,269.905566,270.334741,265.743486,268.538147,50194600,0.0,0.0
2025-11-04 00:00:00-05:00,267.819507,270.973499,267.110866,269.526276,49274800,0.0,0.0
2025-11-05 00:00:00-05:00,268.098980,271.183128,266.422183,269.626099,43683100,0.0,0.0
2025-11-06 00:00:00-05:00,267.380377,272.879874,267.380377,269.256775,51204000,0.0,0.0
2025-11-07 00:00:00-05:00,269.286715,271.771999,266.262481,267.959259,48227400,0.0,0.0

In [6]:
historical_data.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-04-27 00:00:00-04:00,266.089996,268.359985,265.070007,267.609985,41466800,0.0,0.0
2026-04-28 00:00:00-04:00,272.339996,273.230011,268.660004,270.709991,40018900,0.0,0.0
2026-04-29 00:00:00-04:00,267.549988,271.040009,267.040009,270.170013,30047900,0.0,0.0
2026-04-30 00:00:00-04:00,270.500000,276.000000,268.140015,271.350006,91848200,0.0,0.0
2026-05-01 00:00:00-04:00,278.859985,287.220001,278.369995,280.140015,79844600,0.0,0.0